mindmap
  root((Antigrafil))
    Capitulo1[Capitulo1]
        Subcapitulo1
            Subsubcapitulo1
            Subsubcapitulo2
        Subcapitulo2
            Subsubcapitulo1
            Subsubcapitulo2
    Capitulo2(Capitulo2)
        Subcapitulo1
            Subsubcapitulo1
            Subsubcapitulo2
        Subcapitulo2
            Subsubcapitulo1
            Subsubcapitulo2
